#turtle.home() # 是讓烏龜回到原點的指令
#turtle.stamp()  #蓋章
# turtle.penup() #提筆
import turtle

turtle.stamp()
turtle.left(90)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.home()
turtle.right(45)
turtle.penup()
turtle.forward(100)
turtle.stamp()
turtle.done()